# Generated by Django 2.1.2 on 2019-04-12 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='team_register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_1', models.CharField(max_length=200)),
                ('player_2', models.CharField(max_length=200)),
                ('team_name', models.CharField(max_length=200, unique=True)),
                ('game_type', models.CharField(choices=[('FB', 'Foosball'), ('TT', 'Table Tennis')], max_length=2)),
                ('points', models.IntegerField(default=0)),
            ],
        ),
    ]
