# Generated by Django 2.1.2 on 2019-04-15 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manage_team', '0004_auto_20190415_1405'),
    ]

    operations = [
        migrations.AddField(
            model_name='teaminfo',
            name='player_2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player2', to='manage_team.PlayerInfo'),
        ),
        migrations.AlterField(
            model_name='teaminfo',
            name='player_1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player1', to='manage_team.PlayerInfo'),
        ),
    ]
