# Generated by Django 2.1.2 on 2019-04-15 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manage_team', '0005_auto_20190415_1410'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='teaminfo',
            unique_together={('player_1', 'player_2')},
        ),
    ]
