# Generated by Django 2.1.2 on 2019-04-15 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manage_team', '0006_auto_20190415_1414'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='teaminfo',
            unique_together={('player_2', 'player_1')},
        ),
    ]
