# Generated by Django 2.1.2 on 2019-04-15 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manage_team', '0007_auto_20190415_1418'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='teaminfo',
            unique_together=set(),
        ),
    ]
