# Generated by Django 2.1.2 on 2019-04-16 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manage_team', '0008_auto_20190415_1421'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaderBoard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField(default=0)),
                ('team_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manage_team.TeamInfo')),
            ],
        ),
        migrations.AddField(
            model_name='gameinfo',
            name='winning_points',
            field=models.IntegerField(default=0),
        ),
    ]
