# Generated by Django 2.1.2 on 2019-04-16 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manage_team', '0009_auto_20190416_1011'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leaderboard',
            name='team_name',
        ),
        migrations.DeleteModel(
            name='LeaderBoard',
        ),
    ]
